version: '3.8'

services:

  persona-service:
    build: PersoanService/.
    container_name: persona-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - async-net

  cuenta-service:
    build: CuentaService/.
    container_name: cuenta-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - async-net

networks:
  async-net: