version: '3.8'

services:

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - async-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - async-net

  persona-db:
    image: postgres:16
    container_name: persona-db
    environment:
      POSTGRES_DB: persona_db
      POSTGRES_USER: persona_user
      POSTGRES_PASSWORD: persona_pass
    ports:
      - "5433:5432"
    networks:
      - async-net
    volumes:
      - persona-data:/var/lib/postgresql/data

  cuenta-db:
    image: postgres:16
    container_name: cuenta-db
    environment:
      POSTGRES_DB: cuenta_db
      POSTGRES_USER: cuenta_user
      POSTGRES_PASSWORD: cuenta_pass
    ports:
      - "5434:5432"
    networks:
      - async-net
    volumes:
      - cuenta-data:/var/lib/postgresql/data

  persona-service:
    build: ./PersonaService
    container_name: persona-service
    depends_on:
      - persona-db
      - kafka
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://persona-db:5432/persona_db
      SPRING_DATASOURCE_USERNAME: persona_user
      SPRING_DATASOURCE_PASSWORD: persona_pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - async-net

  cuenta-service:
    build: ./CuentaService
    container_name: cuenta-service
    depends_on:
      - cuenta-db
      - kafka
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cuenta-db:5432/cuenta_db
      SPRING_DATASOURCE_USERNAME: cuenta_user
      SPRING_DATASOURCE_PASSWORD: cuenta_pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - async-net

networks:
  async-net:

volumes:
  persona-data:
  cuenta-data: