
CREATE TABLE cuenta (
    cuenta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta VARCHAR(20) NOT NULL UNIQUE,
    tipo_cuenta VARCHAR(20) NOT NULL,
    saldo DECIMAL(18,2) NOT NULL DEFAULT 0,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    cliente_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cuenta_cliente_id ON cuenta(cliente_id);
CREATE INDEX idx_cuenta_numero ON cuenta(numero_cuenta);

CREATE TABLE movimiento (
    movimiento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id BIGINT NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo_movimiento VARCHAR(20) NOT NULL,
    valor DECIMAL(18,2) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    saldo_inicial DECIMAL(18,2) NOT NULL,
    saldo_disponible DECIMAL(18,2) NOT NULL,

    CONSTRAINT fk_mov_cuenta
        FOREIGN KEY (cuenta_id)
            REFERENCES cuenta (cuenta_id)
            ON DELETE CASCADE
);

CREATE INDEX idx_mov_cuenta_id ON movimiento(cuenta_id);
CREATE INDEX idx_mov_fecha ON movimiento(fecha);

CREATE TABLE client_snapshot (
    client_id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    identification VARCHAR(20) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);